---
  - name: reload systemd daemon
    systemd:
      name: kafka.service
      daemon_reload: yes

  - name: start kafka service
    systemd:
      name: kafka.service
      state: restarted
      enabled: yes
