---
# defaults file for zk
zk_install_parent_dir: /opt/downloads
zk_ver: 3.4.14
zk_file_name: zookeeper-{{ zk_ver }}.tgz
zk_name: zookeeper-{{ zk_ver }}
zk_install_dir: '{{ zk_install_parent_dir }}/{{ zk_name }}'
zk_install_link_dir: '{{ zk_install_parent_dir }}/zk'
zk_mirror: http://mirror.ox.ac.uk/sites/rsync.apache.org/zookeeper/zookeeper-{{ zk_ver }}/zookeeper-{{ zk_ver }}.gz
data_basepath: "/var/data"
#########################################ZOOKEEPER PROPERTIES ################################
zookeeper_connection_timeout_ms: 1000000
zookeeper_data_dir: "{{ data_basepath }}/zookeeper"
zookeeper_max_cnxns: 0
zookeeper_init_limit: 5
zookeeper_sync_limit: 3
zookeeper_tickTime: 2000
zookeeper_group: "{{ groups['zookeeper'] | default(ansible_play_hosts) }}"
